# Generated by Django 5.2.12 on 2026-04-06 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_appointment_type_appointment_channel_and_more'),
        ('patients', '0002_patient_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de atencion')),
                ('encounter_type', models.CharField(choices=[('FIRST_VISIT', 'Primera consulta'), ('FOLLOW_UP', 'Control'), ('PROCEDURE', 'Procedimiento'), ('URGENT', 'Urgencia'), ('TELEMEDICINE', 'Telemedicina')], default='FIRST_VISIT', max_length=20, verbose_name='Tipo de atencion')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SIGNED', 'Firmada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('chief_complaint', models.CharField(max_length=255, verbose_name='Motivo de consulta')),
                ('vitals_summary', models.CharField(blank=True, max_length=255, verbose_name='Signos vitales')),
                ('subjective', models.TextField(blank=True, verbose_name='Subjetivo')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo')),
                ('assessment', models.TextField(blank=True, verbose_name='Analisis')),
                ('plan', models.TextField(blank=True, verbose_name='Plan terapeutico')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_encounters', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_encounters', to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_encounters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-encounter_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('document_type', models.CharField(choices=[('CONSENT', 'Consentimiento'), ('RESULT', 'Resultado'), ('CERTIFICATE', 'Certificado'), ('NOTE', 'Nota'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo de documento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('file', models.FileField(blank=True, upload_to='clinical_documents/%Y/%m/', verbose_name='Archivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_documents', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clinical.clinicalencounter')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Principal'), ('SECONDARY', 'Secundario'), ('WORKING', 'Impresion diagnostica')], default='PRIMARY', max_length=20, verbose_name='Tipo')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Codigo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.clinicalencounter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('LAB', 'Laboratorio'), ('IMAGING', 'Imagen'), ('PROCEDURE', 'Procedimiento'), ('INTERCONSULT', 'Interconsulta'), ('OTHER', 'Otro')], default='LAB', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('SCHEDULED', 'Agendada'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='REQUESTED', max_length=20, verbose_name='Estado')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('instructions', models.TextField(blank=True, verbose_name='Indicaciones')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('result_summary', models.TextField(blank=True, verbose_name='Resultado resumido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinical.clinicalencounter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=160, verbose_name='Medicamento')),
                ('presentation', models.CharField(blank=True, max_length=120, verbose_name='Presentacion')),
                ('route', models.CharField(blank=True, max_length=80, verbose_name='Via')),
                ('dosage', models.CharField(max_length=120, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=120, verbose_name='Frecuencia')),
                ('duration_days', models.PositiveSmallIntegerField(default=1, verbose_name='Duracion (dias)')),
                ('instructions', models.TextField(blank=True, verbose_name='Indicaciones')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.clinicalencounter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
