# Generated by Django 5.2.12 on 2026-04-05 23:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_appointment_type_appointment_channel_and_more'),
        ('patients', '0002_patient_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Cobro'), ('REFUND', 'Reembolso'), ('EXPENSE', 'Egreso')], default='PAYMENT', max_length=20, verbose_name='Tipo')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('LINK', 'Link de pago'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Metodo de pago')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto')),
                ('concept', models.CharField(max_length=160, verbose_name='Concepto')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at', '-id'],
            },
        ),
    ]
