# Generated by Django 5.2.12 on 2026-04-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_coverageagreement_invoice_cashtransaction_invoice'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operations.location'),
        ),
    ]
