# Generated by Django 5.2.7 on 2026-01-23 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno del esquema tributario (ej: IVA12, IVA0, EXENTO)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (IVA 12%, IVA 0%, Exento, etc.)', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej. 12.00 para IVA 12%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_sales', models.BooleanField(default=True)),
                ('applies_purchases', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esquema Tributario',
                'verbose_name_plural': 'Esquemas Tributarios',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código corto: kg, g, m, cm, un, caja, etc.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo: Kilogramo, Metro, Unidad, Caja...', max_length=50)),
                ('category', models.CharField(choices=[('MASS', 'Masa'), ('LENGTH', 'Longitud'), ('COUNT', 'Unidad (pieza, rollo, etc.)'), ('VOLUME', 'Volumen'), ('AREA', 'Área'), ('OTHER', 'Otro')], default='COUNT', max_length=10)),
                ('factor_to_base', models.DecimalField(decimal_places=4, help_text='Factor para convertir a la unidad base de la categoría', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno de bodega (ej: BOD-CUA, BOD-MP, BOD-PT)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Bodega de cuarentena)', max_length=100)),
                ('type', models.CharField(choices=[('QUARANTINE', 'Cuarentena'), ('RAW', 'Materia prima'), ('WIP', 'Semielaborado'), ('FINISHED', 'Producto terminado'), ('SCRAP', 'Producto de baja'), ('RECALL', 'Retiro de mercado'), ('RETURNS', 'Devoluciones de clientes'), ('STAGING', 'Zona de predespacho'), ('SAMPLES', 'Muestras / retención'), ('LABELS', 'Etiquetas'), ('PACK', 'Material de empaque'), ('OTHER', 'Otro')], default='OTHER', help_text='Tipo de bodega según clasificación regulatoria/operativa', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_quarantine', models.BooleanField(default=False, help_text='Usar como bodega de cuarentena por defecto en recepción')),
                ('is_default_for_raw', models.BooleanField(default=False, help_text='Bodega por defecto para materia prima liberada')),
                ('is_default_fg_released', models.BooleanField(default=False, help_text='Bodega por defecto para producto terminado liberado.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código de ubicación (ej: EST-01-N1-A)', max_length=30)),
                ('name', models.CharField(blank=True, help_text='Nombre o alias de la ubicació', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Descripción adicional (pasillo, estante, etc.)', max_length=255, null=True)),
                ('row', models.CharField(blank=True, max_length=10, null=True)),
                ('rack', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'unique_together': {('warehouse', 'code')},
            },
        ),
    ]
