# Generated by Django 5.2.7 on 2026-02-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('legal_name', models.CharField(max_length=300, verbose_name='Razón social')),
                ('trade_name', models.CharField(blank=True, max_length=300, verbose_name='Nombre comercial')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección matriz')),
                ('establishment_code', models.CharField(default='001', help_text='Ej: 001', max_length=3, verbose_name='Código establecimiento')),
                ('emission_point', models.CharField(default='001', help_text='Ej: 001', max_length=3, verbose_name='Punto de emisión')),
                ('special_taxpayer', models.CharField(blank=True, max_length=13, verbose_name='Contribuyente especial Nº')),
                ('obligated_accounting', models.BooleanField(default=True, verbose_name='Obligado a llevar contabilidad')),
                ('environment', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='Ambiente SRI')),
                ('emission_type', models.CharField(default='1', help_text='1 = Emisión normal', max_length=1, verbose_name='Tipo de emisión')),
                ('certificate_file', models.FileField(blank=True, upload_to='sri_certs/', verbose_name='Certificado .p12')),
                ('certificate_password', models.CharField(blank=True, max_length=200, verbose_name='Contraseña del certificado')),
                ('logo', models.ImageField(blank=True, upload_to='company/', verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuración de empresa',
            },
        ),
    ]
