# Generated by Django 5.2.7 on 2026-01-23 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno del socio (ej. PRV-001, CLI-100).', max_length=20, unique=True, verbose_name='Código interno')),
                ('alt_code', models.CharField(blank=True, help_text='Código alterno o de sistema externo (opcional).', max_length=20, null=True, verbose_name='Código alterno')),
                ('identification_type', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'Cédula'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='RUC', max_length=20, verbose_name='Tipo de identificación')),
                ('identification', models.CharField(help_text='RUC / cédula / pasaporte, según corresponda.', max_length=20, verbose_name='Identificación')),
                ('trade_name', models.CharField(blank=True, help_text='Nombre comercial (si aplica).', max_length=150, verbose_name='Nombre comercial')),
                ('legal_name', models.CharField(help_text='Nombre fiscal que aparece en facturas.', max_length=200, verbose_name='Nombre fiscal / razón social')),
                ('category', models.CharField(blank=True, choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C'), ('OTHER', 'Otra')], default='OTHER', max_length=10, verbose_name='Categoría')),
                ('company_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('PERSON', 'Persona natural')], default='COMPANY', max_length=20, verbose_name='Tipo de empresa')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Cliente')),
                ('is_supplier', models.BooleanField(default=True, verbose_name='Proveedor')),
                ('is_public_entity', models.BooleanField(default=False, verbose_name='Entidad pública')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito máximo')),
                ('credit_available', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito disponible')),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito utilizado')),
                ('credit_terms_days', models.PositiveIntegerField(default=0, help_text='Plazo de pago en días (0 = contado).', verbose_name='Días de crédito')),
                ('retention_profile', models.CharField(choices=[('NONE', 'No emite retención'), ('AGENT', 'Agente de retención general'), ('RENT', 'Retención en renta'), ('VAT', 'Retención en IVA'), ('RENT_VAT', 'Retención en renta e IVA')], default='NONE', max_length=20, verbose_name='Perfil de retención')),
                ('branch_name', models.CharField(blank=True, help_text='Sucursal asociada (si aplica).', max_length=100, verbose_name='Sucursal')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=100, verbose_name='País')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Contacto principal')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de contacto')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('is_qualified_supplier', models.BooleanField(default=False, verbose_name='Proveedor calificado ISO 13485')),
                ('qualification_level', models.CharField(blank=True, help_text='Ejemplo: Crítico / No crítico, A / B / C, etc.', max_length=50, verbose_name='Nivel de calificación')),
                ('qualification_date', models.DateField(blank=True, null=True, verbose_name='Fecha de última calificación')),
                ('qualification_notes', models.TextField(blank=True, verbose_name='Notas de calificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio (cliente/proveedor)',
                'verbose_name_plural': 'Socios (clientes y proveedores)',
                'ordering': ['trade_name', 'legal_name'],
            },
        ),
    ]
