# Generated by Django 5.2.7 on 2026-02-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='driver_identification',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula del conductor'),
        ),
        migrations.AddField(
            model_name='partner',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del conductor'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_carrier',
            field=models.BooleanField(default=False, help_text='Marcar si es proveedor de transporte.', verbose_name='Transportista'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Placa del vehículo'),
        ),
    ]
