# Generated by Django 5.2.7 on 2026-02-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_driver_identification_partner_driver_name_and_more'),
        ('sales', '0013_add_price_list_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='sales.pricelist', verbose_name='Lista de precios'),
        ),
    ]
