# Generated by Django 5.2.7 on 2026-02-11 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('partners', '0003_add_price_list_to_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_unit_price', models.DecimalField(decimal_places=4, help_text='Precio al que este proveedor vende este producto', max_digits=12, verbose_name='Precio unitario del proveedor')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=4, default=1, help_text='Cantidad mínima que acepta el proveedor', max_digits=12, verbose_name='Cantidad mínima de pedido')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Días que tarda el proveedor en entregar', verbose_name='Tiempo de entrega (días)')),
                ('supplier_product_code', models.CharField(blank=True, help_text='Código/referencia que usa el proveedor para este producto', max_length=100, verbose_name='Código del producto en catálogo del proveedor')),
                ('is_preferred', models.BooleanField(default=False, help_text='Marcar si es el proveedor preferido para este producto', verbose_name='Proveedor preferido')),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre este producto con este proveedor', verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offerings', to='inventory.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='partners.partner', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto de proveedor',
                'verbose_name_plural': 'Productos de proveedores',
                'ordering': ['supplier__trade_name', 'product__code'],
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
