# Generated by Django 5.2.7 on 2026-04-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantOperationalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("audit", "Audit"), ("health", "Health")], default="audit", max_length=20)),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error")],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("open", "Open"), ("resolved", "Resolved")],
                        default="recorded",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_operational_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_events",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant operational event",
                "verbose_name_plural": "Tenant operational events",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
