# Generated by Django 5.2.12 on 2026-04-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantoperationalevent'),
    ]

    operations = []
