# Generated by Django 5.2.12 on 2026-04-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantoperationalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('clinic_admin', 'Admin de clinica'), ('doctor', 'Profesional'), ('reception', 'Recepcion'), ('cashier', 'Caja'), ('assistant', 'Asistente')], default='assistant', max_length=30),
        ),
    ]
