# Generated by Django 5.2.12 on 2026-04-26 01:57

from django.db import migrations, models


def forward_fill_reports_defaults(apps, schema_editor):
    TenantConfig = apps.get_model("tenants", "TenantConfig")

    from tenants.defaults import merge_with_profile_defaults

    for config in TenantConfig.objects.all():
        merged = merge_with_profile_defaults(
            config.profile,
            feature_flags=config.feature_flags,
            labels=config.labels,
            entity_fields=config.entity_fields,
            module_order=config.module_order,
            dashboard_widgets=config.dashboard_widgets,
            role_policies=config.role_policies,
            document_blueprints=config.document_blueprints,
            pipeline_templates=config.pipeline_templates,
        )
        config.feature_flags = merged["feature_flags"]
        config.labels = merged["labels"]
        config.entity_fields = merged["entity_fields"]
        config.module_order = merged["module_order"]
        config.dashboard_widgets = merged["dashboard_widgets"]
        config.role_policies = merged["role_policies"]
        config.document_blueprints = merged["document_blueprints"]
        config.pipeline_templates = merged["pipeline_templates"]
        config.save(
            update_fields=[
                "feature_flags",
                "labels",
                "entity_fields",
                "module_order",
                "dashboard_widgets",
                "role_policies",
                "document_blueprints",
                "pipeline_templates",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_expand_vertical_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='profile',
            field=models.CharField(choices=[('general', 'General'), ('condominio', 'Administracion de condominios'), ('broker', 'Broker de seguros'), ('servicios', 'Consultoria y servicios corporativos'), ('retail_moda', 'Retail y marcas de ropa'), ('marketing', 'Agencia de marketing (legacy)')], default='general', max_length=30),
        ),
        migrations.RunPython(forward_fill_reports_defaults, migrations.RunPython.noop),
    ]
