# Generated by Django 5.2.12 on 2026-08-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_enable_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='profile',
            field=models.CharField(choices=[('general', 'General'), ('condominio', 'Operacion de condominios'), ('broker', 'Broker de seguros'), ('servicios', 'Servicios B2B'), ('retail_moda', 'Retail y clienteling'), ('marketing', 'Agencia comercial')], default='general', max_length=30),
        ),
    ]
