# Generated by Django 5.2.12 on 2026-05-07 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binncrm', '0009_activity_binn_activity_due_idx_and_more'),
        ('collab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', 'last_message_at'], name='collab_conversation_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmembership',
            index=models.Index(fields=['user', 'is_active', 'conversation'], name='collab_member_user_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='collab_message_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['author', 'created_at'], name='collab_message_author_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='collab_notification_user_idx'),
        ),
    ]
