# Generated by Django 5.2.12 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0002_conversation_collab_conversation_recent_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmembership",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversationmembership",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="conversationmembership",
            index=models.Index(
                fields=["user", "is_active", "is_archived", "is_pinned"],
                name="collab_member_inbox_idx",
            ),
        ),
    ]
