# Generated by Django 5.2.13 on 2026-09-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binncrm', '0012_objectrecord_assessment_submission_objectrecord_deal_and_more'),
        ('collab', '0004_backfill_membership_last_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='binncrm.objectrecord'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('team', 'Equipo'), ('entity', 'Ficha'), ('deal', 'Deal'), ('project', 'Proyecto')], default='team', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('kind', 'project'), name='collab_unique_project_conversation'),
        ),
    ]
