# Generated by Django 5.2.7 on 2026-01-23 21:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.CharField(default='1', help_text='Versión del plano (1, 1.1, A, B, etc.)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Descripción general del plano / notas técnicas.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product_finished', models.ForeignKey(limit_choices_to={'is_active': True, 'product_type': 'FG'}, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product', verbose_name='Producto terminado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano de fabricación',
                'verbose_name_plural': 'Planos de fabricación',
                'unique_together': {('product_finished', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Cantidad requerida por unidad de producto terminado (en unidad base del componente).', max_digits=12)),
                ('scrap_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de merma / desperdicio esperado (0–100).', max_digits=5)),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Orden lógico del componente en el plano.')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterial', verbose_name='BOM')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='inventory.product', verbose_name='Componente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de BOM',
                'verbose_name_plural': 'Líneas de BOM',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ej: PP-2026-0001', max_length=30, unique=True, verbose_name='Código del plan')),
                ('lot_code', models.CharField(help_text='Ej: CAP012026. Debe ser único por producto y fecha.', max_length=50, verbose_name='Código de lote de producción')),
                ('manufacturing_date', models.DateField(verbose_name='Fecha de fabricación del lote')),
                ('quantity_planned', models.DecimalField(decimal_places=2, help_text='Ej: 10000 unidades para el lote completo.', max_digits=12, verbose_name='Cantidad total planificada del lote')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('CANCELED', 'Anulado')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'is_active': True, 'product_type': 'FG'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='inventory.product', verbose_name='Producto terminado (SKU)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de producción',
                'verbose_name_plural': 'Planes de producción',
                'unique_together': {('product', 'lot_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la ruta (ej: Ruta estándar, Ruta alternativa...).', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Producto que se fabrica con esta ruta (normalmente SEMI o FG).', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta de producción',
                'verbose_name_plural': 'Rutas de producción',
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno de la orden (ej: OP-2025-0001).', max_length=50, unique=True)),
                ('quantity_planned', models.DecimalField(decimal_places=2, help_text='Cantidad planificada de producto terminado.', max_digits=12)),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad realmente producida .', max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RELEASED', 'Liberada'), ('IN_PROGRESS', 'En proceso'), ('DONE', 'Terminada'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20)),
                ('origin_type', models.CharField(choices=[('PLANNING', 'Planificación interna'), ('SALES_ORDER', 'Pedido de cliente')], default='PLANNING', max_length=20)),
                ('origin_reference', models.CharField(blank=True, help_text='Referencia externa: código de pedido u planficación de la produción.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.billofmaterial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_lot', models.ForeignKey(blank=True, help_text='Lote de producto terminado asociado a esta OP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_finished_in_orders', to='inventory.lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Plan de producción del que nace esta OP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='production.productionplan')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productroute')),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
            },
        ),
        migrations.CreateModel(
            name='ProductRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text='Orden del paso en la ruta (1, 2, 3...).')),
                ('name', models.CharField(help_text='Nombre corto del paso (ej: Crochet, Corte, Ensamblado).', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descripción de lo que se hace en este paso.', max_length=255, null=True)),
                ('expected_duration_min', models.PositiveIntegerField(blank=True, help_text='Duración esperada en minutos por lote/orden (opcional).', null=True)),
                ('requires_qa', models.BooleanField(default=False, help_text='Si está marcado, la orden puede exigir una inspección QA en este paso.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productroute')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paso de ruta de producción',
                'verbose_name_plural': 'Pasos de ruta de producción',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text='Orden de la operación dentro de la OP (normalmente coincide con step.sequence).')),
                ('quantity_input', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_output', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('DONE', 'Completada')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('input_lot', models.ForeignKey(blank=True, help_text='Lote de entrada (producto en proceso).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_input', to='inventory.lot')),
                ('output_lot', models.ForeignKey(blank=True, help_text='Lote resultante de esta operación (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_output', to='inventory.lot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.productionorder')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='production.productroutestep')),
            ],
            options={
                'verbose_name': 'Operación de producción',
                'verbose_name_plural': 'Operaciones de producción',
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno del centro de trabajo (ej: Estación-01)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Estación que hace algo")', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad teórica por hora (solo referencial).', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_warehouse', models.ForeignKey(blank=True, help_text='Bodega por defecto donde se almacena el producto en proceso de este centro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_centers', to='core.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centro de trabajo',
                'verbose_name_plural': 'Centros de trabajo',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='productroutestep',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_steps', to='production.workcenter'),
        ),
        migrations.CreateModel(
            name='ProductionPlanRawLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad teórica de consumo de este lote de MP en el plan.', max_digits=12, null=True)),
                ('component', models.ForeignKey(limit_choices_to={'is_active': True, 'product_type': 'RAW'}, on_delete=django.db.models.deletion.PROTECT, related_name='as_component_in_plans', to='inventory.product')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_plans', to='inventory.lot')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_lots', to='production.productionplan')),
            ],
            options={
                'unique_together': {('plan', 'component')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productroutestep',
            unique_together={('route', 'sequence')},
        ),
    ]
