# Generated by Django 5.2.7 on 2026-01-27 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialline',
            name='scrap_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje de merma / desperdicio esperado (0–100).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productionoperation',
            name='quantity_input',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionoperation',
            name='quantity_output',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad planificada de producto terminado.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Cantidad realmente producida .', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=4, help_text='Ej: 10000 unidades para el lote completo.', max_digits=12, verbose_name='Cantidad total planificada del lote'),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='capacity_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Capacidad teórica por hora (solo referencial).', max_digits=12, null=True),
        ),
    ]
