# Generated by Django 5.2.7 on 2026-01-29 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('production', '0002_alter_billofmaterialline_scrap_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoperation',
            name='materials_consumed',
            field=models.BooleanField(default=False, help_text='Indica si ya se consumió la materia prima en este paso (evita doble consumo).'),
        ),
        migrations.AlterField(
            model_name='billofmaterialline',
            name='component',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'product_type__in': ['RAW', 'SEMI']}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='inventory.product', verbose_name='Componente'),
        ),
        migrations.AlterField(
            model_name='billofmaterialline',
            name='scrap_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje estimado de merma para planificación (0–1). La merma real se calcula al cerrar la OP.', max_digits=5),
        ),
    ]
