# Generated by Django 5.2.7 on 2026-01-29 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionoperation_materials_consumed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoperation',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Operario responsable de ejecutar este paso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionoperation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('PAUSED', 'Pausada'), ('HOLD', 'En espera (QA / bloqueo)'), ('DONE', 'Completada'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20),
        ),
    ]
