# Generated by Django 5.2.7 on 2026-01-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_stock_quantity'),
        ('production', '0005_operationstatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=4, help_text='Cantidad calculada del plan a transferir.', max_digits=12)),
                ('quantity_confirmed', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad que el operario confirma haber transferido.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('ADJUSTED', 'Ajustada (con desviación)')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('deviation_notes', models.TextField(blank=True, help_text='Notas del operario si la cantidad difiere de lo solicitado.', null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_transfers', to='inventory.product')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='core.warehouse')),
                ('inventory_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transfers', to='inventory.inventorymove')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_transfers', to='inventory.lot')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_transfers', to='production.productionorder')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='core.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de material',
                'verbose_name_plural': 'Transferencias de material',
                'unique_together': {('order', 'lot')},
            },
        ),
    ]
