# Generated by Django 5.2.7 on 2026-01-29 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_materialtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoperation',
            name='planned_end',
            field=models.DateTimeField(blank=True, help_text='Fin planificado (calculado al liberar).', null=True),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='planned_start',
            field=models.DateTimeField(blank=True, help_text='Inicio planificado (calculado al liberar).', null=True),
        ),
        migrations.AddField(
            model_name='productroutestep',
            name='setup_time_min',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo de setup específico de este paso (minutos). Si es 0 usa el del centro de trabajo.'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='efficiency_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Factor de eficiencia real (ej: 0.85 = 85%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='hours_per_shift',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Horas productivas por turno.', max_digits=5),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='num_machines',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de máquinas o puestos paralelos en esta estación.'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='num_operators',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de operarios disponibles en esta estación.'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='setup_time_min',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo de setup/preparación por lote (minutos).'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='shifts_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de turnos por día.'),
        ),
        migrations.AlterField(
            model_name='productroutestep',
            name='expected_duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Duración esperada en minutos por unidad de producto.', null=True),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='capacity_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Capacidad teórica por hora (unidades/hora).', max_digits=12, null=True),
        ),
    ]
