# Generated by Django 5.2.7 on 2026-02-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_productionoperation_planned_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productroutestep',
            name='is_conversion_point',
            field=models.BooleanField(default=False, help_text='Marca el paso donde la unidad cambia de MP a PT (ej: de metros a unidades).'),
        ),
    ]
