# Generated by Django 5.2.7 on 2026-02-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('production', '0008_add_conversion_point_to_routestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationComponentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_input', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de entrada (auto-llenada desde paso anterior o transferencia).', max_digits=14, null=True)),
                ('quantity_output', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad de salida registrada por el operario.', max_digits=14, null=True)),
                ('bom_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_details', to='production.billofmaterialline')),
                ('component', models.ForeignKey(help_text='Componente (redundante con bom_line, facilita queries).', on_delete=django.db.models.deletion.CASCADE, related_name='operation_component_details', to='inventory.product')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_details', to='production.productionoperation')),
            ],
            options={
                'verbose_name': 'Detalle de componente en operación',
                'verbose_name_plural': 'Detalles de componente en operación',
                'ordering': ['bom_line__sequence'],
                'unique_together': {('operation', 'bom_line')},
            },
        ),
    ]
