# Generated by Django 5.2.7 on 2026-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='quantity_current',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='quantity_displayed',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventorymove',
            name='unit_displayed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
    ]
