# Generated by Django 5.2.7 on 2026-01-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_lot_quantity_current_remove_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
