# Generated by Django 5.2.7 on 2026-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lot',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Número de lote único para trazabilidad (del proveedor o auto-generado)', max_length=50, null=True, verbose_name='Número de lote'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='internal_lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('product', 'lot_number')},
        ),
    ]
