# Generated by Django 5.2.7 on 2026-02-11 12:02

from django.db import migrations


def consolidate_lot_numbers(apps, schema_editor):
    """
    Consolida supplier_lot e internal_lot en un solo campo lot_number.
    Prioridad: supplier_lot si existe, sino internal_lot.
    """
    Lot = apps.get_model('inventory', 'Lot')

    for lot in Lot.objects.all():
        # Priorizar lote del proveedor si existe
        if lot.supplier_lot:
            lot.lot_number = lot.supplier_lot
        elif lot.internal_lot:
            lot.lot_number = lot.internal_lot
        else:
            # Si no hay ninguno, generar uno automático
            lot.lot_number = f"LOT-{lot.product.code}-{lot.id}"

        lot.save(update_fields=['lot_number'])


def reverse_consolidate(apps, schema_editor):
    """
    Reversión: copiar lot_number de vuelta a internal_lot
    """
    Lot = apps.get_model('inventory', 'Lot')

    for lot in Lot.objects.all():
        if lot.lot_number and not lot.internal_lot:
            lot.internal_lot = lot.lot_number
            lot.save(update_fields=['internal_lot'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_lot_unique_together_lot_lot_number_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_lot_numbers, reverse_consolidate),
    ]
