# Generated by Django 5.2.12 on 2026-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binncrm', '0003_collectionrecord_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_provider',
            field=models.CharField(choices=[('s3', 'S3 / compatible'), ('external', 'URL externa'), ('manual', 'Referencia manual')], default='s3', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Llamada'), ('whatsapp', 'WhatsApp'), ('note', 'Nota'), ('email', 'Correo'), ('task', 'Tarea'), ('claim', 'Siniestro')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
