# Generated by Django 5.2.12 on 2026-05-07 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binncrm', '0008_collectionrecord_sort_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'completed_at', 'due_at'], name='binn_activity_due_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['entity', 'created_at'], name='binn_act_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['is_active', 'status', 'due_on'], name='binn_collection_due_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrecord',
            index=models.Index(fields=['status', 'sort_order', 'due_on'], name='binn_collection_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['is_active', 'status', 'pipeline', 'stage'], name='binn_deal_flow_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline', 'stage', 'sort_order'], name='binn_deal_stage_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_on'], name='binn_deal_close_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['is_active', 'status', 'valid_until'], name='binn_proposal_status_idx'),
        ),
    ]
