# Generated by Django 5.2.13 on 2026-09-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binncrm', '0011_alter_activity_activity_type_assessmenttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrecord',
            name='assessment_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_records', to='binncrm.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='objectrecord',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_records', to='binncrm.deal'),
        ),
        migrations.AddField(
            model_name='objectrecord',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_records', to='binncrm.entity'),
        ),
        migrations.AddField(
            model_name='objectrecord',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_records', to='binncrm.proposal'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='source_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='binncrm.assessmentsubmission'),
        ),
    ]
