# Generated by Django 5.2.12 on 2026-04-05 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('FIRST_VISIT', 'Primera vez'), ('FOLLOW_UP', 'Control'), ('PROCEDURE', 'Procedimiento'), ('EXAM', 'Examen'), ('OTHER', 'Otro')], default='FIRST_VISIT', max_length=20, verbose_name='Tipo de cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='channel',
            field=models.CharField(choices=[('PHONE', 'Telefono'), ('WHATSAPP', 'WhatsApp'), ('WEB', 'Web'), ('WALK_IN', 'Presencial'), ('REFERRAL', 'Referido')], default='PHONE', max_length=20, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='front_desk_notes',
            field=models.TextField(blank=True, verbose_name='Notas de recepcion'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('CHECKED_IN', 'Check-in'), ('IN_PROGRESS', 'En atencion'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada'), ('NO_SHOW', 'No asistio')], default='SCHEDULED', max_length=20),
        ),
    ]
