# Generated by Django 5.2.12 on 2026-04-05 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_emergency_contact_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('source', models.CharField(choices=[('WEBSITE', 'Web'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Telefono'), ('WALK_IN', 'Presencial'), ('REFERRAL', 'Referido'), ('CAMPAIGN', 'Campana'), ('INSURER', 'Aseguradora'), ('OTHER', 'Otro')], default='WHATSAPP', max_length=20, verbose_name='Origen')),
                ('stage', models.CharField(choices=[('NEW', 'Nuevo'), ('CONTACTED', 'Contactado'), ('QUALIFIED', 'Calificado'), ('APPOINTMENT', 'Cita agendada'), ('WON', 'Ganado'), ('LOST', 'Perdido')], default='NEW', max_length=20, verbose_name='Etapa')),
                ('interested_service', models.CharField(blank=True, max_length=160, verbose_name='Servicio de interes')),
                ('next_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='Proximo contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='patients.patient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', 'full_name'],
            },
        ),
    ]
