# Generated by Django 5.2.7 on 2026-01-23 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('RAW', 'Ingreso materia prima'), ('WIP', 'En proceso'), ('FG', 'Producto terminado')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Si se deja vacío, puede aplicarse por tipo de producto o genérico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_plans', to='inventory.product')),
                ('route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_plans', to='production.productroutestep')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_plans', to='production.workcenter')),
            ],
            options={
                'verbose_name': 'Plan de QA',
                'verbose_name_plural': 'Planes de QA',
            },
        ),
        migrations.CreateModel(
            name='QAParameterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ANCHO, PESO, COLOR, etc.', max_length=50)),
                ('label', models.CharField(help_text='Etiqueta visible en el formulario', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='cm, kg, g/m2...', max_length=20, null=True)),
                ('data_type', models.CharField(choices=[('BOOL', 'Si / No'), ('NUMBER', 'Numérico'), ('TEXT', 'Texto libre')], default='TEXT', max_length=10)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality.qaplan')),
            ],
            options={
                'verbose_name': 'Parámetro de QA',
                'verbose_name_plural': 'Parámetros de QA',
                'ordering': ['plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('RAW', 'Ingreso materia prima'), ('WIP', 'En proceso'), ('FG', 'Producto terminado')], help_text='Etapa del proceso en la que se realiza la inspección.', max_length=10)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.JSONField(blank=True, help_text='Resultados detallados de parámetros (ancho, peso, etc.)', null=True)),
                ('result', models.CharField(blank=True, choices=[('PENDING', 'Pendiente de inspección'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('QUARANTINE', 'Cuarentena')], help_text='Resultado global de la inspección.', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_inspections', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory.lot')),
                ('operation', models.ForeignKey(blank=True, help_text='Operación específica asociada a esta inspección (WIP).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='production.productionoperation')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan de QA aplicado a esta inspección.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='quality.qaplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspección de Calidad',
                'verbose_name_plural': 'Inspecciones de Calidad',
            },
        ),
    ]
