# Generated by Django 5.2.7 on 2026-02-03 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('partners', '0002_partner_driver_identification_partner_driver_name_and_more'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('NOTIFYING', 'Notificando clientes'), ('RECOVERING', 'Recuperando producto'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Severidad')),
                ('recall_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de retiro')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('reason', models.TextField(verbose_name='Motivo detallado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del problema')),
                ('corrective_action', models.TextField(blank=True, verbose_name='Acción correctiva')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro de mercado',
                'verbose_name_plural': 'Retiros de mercado',
                'ordering': ['-recall_date'],
            },
        ),
        migrations.CreateModel(
            name='RecallLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_affected', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad afectada')),
                ('quantity_in_warehouse', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='En bodega')),
                ('quantity_with_clients', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Con clientes')),
                ('quantity_recovered', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad recuperada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_records', to='inventory.lot', verbose_name='Lote')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='quality.productrecall', verbose_name='Retiro')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote afectado',
                'verbose_name_plural': 'Lotes afectados',
                'unique_together': {('recall', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='RecallAffectedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('client_address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('client_city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('dispatch_code', models.CharField(blank=True, max_length=50, verbose_name='Código despacho')),
                ('dispatch_date', models.DateField(blank=True, null=True, verbose_name='Fecha despacho')),
                ('quantity_dispatched', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad despachada')),
                ('notified', models.BooleanField(default=False, verbose_name='Notificado')),
                ('notified_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha notificación')),
                ('notification_method', models.CharField(blank=True, max_length=100, verbose_name='Método')),
                ('recovered', models.BooleanField(default=False, verbose_name='Producto recuperado')),
                ('quantity_recovered', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad recuperada')),
                ('recovery_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha recuperación')),
                ('recovery_notes', models.TextField(blank=True, verbose_name='Notas de recuperación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recall_notifications', to='partners.partner', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_clients', to='quality.productrecall', verbose_name='Retiro')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('recall_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='quality.recalllot', verbose_name='Lote afectado')),
            ],
            options={
                'verbose_name': 'Cliente afectado',
                'verbose_name_plural': 'Clientes afectados',
            },
        ),
        migrations.CreateModel(
            name='RecallOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('origin_type', models.CharField(choices=[('NON_CONFORMITY', 'Producto no conforme'), ('HEALTH_RISK', 'Riesgo para la salud'), ('REGULATORY', 'Notificación de ente regulador'), ('QUALITY_ISSUE', 'Problema de calidad detectado'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Origen de retiro',
                'verbose_name_plural': 'Orígenes de retiro',
                'ordering': ['origin_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productrecall',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='quality.recallorigin', verbose_name='Origen'),
        ),
    ]
