#!/usr/bin/env python
"""Migrar datos de lotes en el schema público manualmente."""

import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django_tenants.utils import schema_context
from inventory.models import Lot
from procurement.models import RawMaterialReceptionLine

print("=" * 80)
print("MIGRANDO DATOS DE LOTES EN SCHEMA PUBLIC")
print("=" * 80)

with schema_context('public'):
    # Migrar lotes de inventario
    print("\n1. Migrando inventory.Lot")
    print("-" * 80)

    lots_updated = 0
    lots_with_supplier = 0
    lots_with_internal = 0
    lots_autogenerated = 0

    for lot in Lot.objects.all():
        old_lot_number = lot.lot_number

        # Priorizar lote del proveedor si existe
        if lot.supplier_lot:
            lot.lot_number = lot.supplier_lot
            lots_with_supplier += 1
        elif lot.internal_lot:
            lot.lot_number = lot.internal_lot
            lots_with_internal += 1
        else:
            # Si no hay ninguno, generar uno automático
            lot.lot_number = f"LOT-{lot.product.code}-{lot.id}"
            lots_autogenerated += 1

        if old_lot_number != lot.lot_number:
            lot.save(update_fields=['lot_number'])
            lots_updated += 1
            print(f"  Lot {lot.id}: '{old_lot_number}' -> '{lot.lot_number}'")

    print(f"\n  Total procesados: {Lot.objects.count()}")
    print(f"  Actualizados: {lots_updated}")
    print(f"  Con supplier_lot: {lots_with_supplier}")
    print(f"  Con internal_lot: {lots_with_internal}")
    print(f"  Auto-generados: {lots_autogenerated}")

    # Migrar líneas de recepción
    print("\n2. Migrando procurement.RawMaterialReceptionLine")
    print("-" * 80)

    lines_updated = 0
    lines_with_supplier = 0
    lines_with_internal = 0
    lines_empty = 0

    for line in RawMaterialReceptionLine.objects.all():
        old_lot_number = line.lot_number

        # Priorizar lote del proveedor si existe
        if line.supplier_lot:
            line.lot_number = line.supplier_lot
            lines_with_supplier += 1
        elif line.internal_lot:
            line.lot_number = line.internal_lot
            lines_with_internal += 1
        else:
            # Si no hay ninguno, dejar vacío (se generará en la recepción)
            lines_empty += 1

        if old_lot_number != line.lot_number:
            line.save(update_fields=['lot_number'])
            lines_updated += 1
            print(f"  Line {line.id} (Reception {line.reception.code}): '{old_lot_number}' -> '{line.lot_number}'")

    print(f"\n  Total procesados: {RawMaterialReceptionLine.objects.count()}")
    print(f"  Actualizados: {lines_updated}")
    print(f"  Con supplier_lot: {lines_with_supplier}")
    print(f"  Con internal_lot: {lines_with_internal}")
    print(f"  Vacíos: {lines_empty}")

    # Verificar resultados
    print("\n3. Verificación final")
    print("-" * 80)

    lots_without_lot_number = Lot.objects.filter(lot_number__isnull=True).count() + Lot.objects.filter(lot_number='').count()
    lines_without_lot_number = RawMaterialReceptionLine.objects.filter(lot_number__isnull=True).count() + RawMaterialReceptionLine.objects.filter(lot_number='').count()

    print(f"  Lotes sin lot_number: {lots_without_lot_number}")
    print(f"  Líneas sin lot_number: {lines_without_lot_number}")

    if lots_without_lot_number == 0 and lines_without_lot_number == 0:
        print("\n  [OK] Migración completada exitosamente!")
    else:
        print("\n  [WARNING] Aún hay registros sin lot_number")

print("\n" + "=" * 80)
print("MIGRACIÓN COMPLETADA")
print("=" * 80)
