# Generated by Django 5.2.12 on 2026-04-06 17:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_appointment_type_appointment_channel_and_more'),
        ('billing', '0002_coverageagreement_invoice_cashtransaction_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('trigger', models.CharField(choices=[('APPOINTMENT_REMINDER', 'Recordatorio de cita'), ('FOLLOW_UP', 'Seguimiento post consulta'), ('INVOICE_OVERDUE', 'Factura vencida'), ('LOW_STOCK_ALERT', 'Alerta de inventario')], max_length=30, verbose_name='Disparador')),
                ('channel', models.CharField(choices=[('INTERNAL', 'Interno'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('TASK', 'Tarea')], default='INTERNAL', max_length=20, verbose_name='Canal')),
                ('target_role', models.CharField(blank=True, max_length=30, verbose_name='Rol destino')),
                ('offset_minutes', models.IntegerField(default=0, verbose_name='Offset minutos')),
                ('template_text', models.TextField(blank=True, verbose_name='Plantilla')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima ejecucion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitosa'), ('WARNING', 'Con alertas'), ('ERROR', 'Error')], default='SUCCESS', max_length=20, verbose_name='Estado')),
                ('summary', models.CharField(max_length=255, verbose_name='Resumen')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ejecutada en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='operations.automationrule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('applies_to_role', models.CharField(blank=True, max_length=30, verbose_name='Rol aplicable')),
                ('basis', models.CharField(choices=[('COLLECTION', 'Cobros'), ('INVOICE', 'Facturacion')], default='COLLECTION', max_length=20, verbose_name='Base')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje')),
                ('flat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Fijo por evento')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('provider', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PAYMENTS', 'Pasarela de pago'), ('LAB', 'Laboratorio'), ('BI', 'BI / Data')], max_length=20, verbose_name='Proveedor')),
                ('status', models.CharField(choices=[('CONFIGURED', 'Configurada'), ('TESTING', 'En pruebas'), ('ERROR', 'Error'), ('DISABLED', 'Desactivada')], default='TESTING', max_length=20, verbose_name='Estado')),
                ('endpoint', models.CharField(blank=True, max_length=255, verbose_name='Endpoint o URL')),
                ('secret_hint', models.CharField(blank=True, max_length=40, verbose_name='Referencia de credencial')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Direccion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='Periodo desde')),
                ('period_end', models.DateField(verbose_name='Periodo hasta')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comision')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('PAID', 'Pagada'), ('VOID', 'Anulada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to=settings.AUTH_USER_MODEL)),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_records', to='billing.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='operations.commissionscheme')),
            ],
            options={
                'ordering': ['-period_end', '-commission_amount', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'appointment'), name='operations_unique_provider_appointment_commission')],
            },
        ),
    ]
