# Generated by Django 5.2.12 on 2026-04-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono de emergencia'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_plan',
            field=models.CharField(blank=True, max_length=120, verbose_name='Plan/Convenio'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=120, verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='patient',
            name='marketing_opt_in',
            field=models.BooleanField(default=True, verbose_name='Acepta recordatorios y promociones'),
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas administrativas'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono responsable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='source',
            field=models.CharField(choices=[('ORGANIC', 'Organico'), ('REFERRAL', 'Referido'), ('WHATSAPP', 'WhatsApp'), ('CAMPAIGN', 'Campana'), ('WALK_IN', 'Espontaneo'), ('INSURER', 'Aseguradora'), ('OTHER', 'Otro')], default='ORGANIC', max_length=20, verbose_name='Origen'),
        ),
    ]
