# Generated by Django 5.2.7 on 2026-01-23 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de orden')),
                ('order_date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de emisión')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada al proveedor'), ('CONFIRMED', 'Confirmada'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Moneda')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total de la orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partner', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Precio unitario')),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Total de la línea')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder', verbose_name='Orden de compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.product', verbose_name='Producto')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='core.unit', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Línea de orden de compra',
                'verbose_name_plural': 'Líneas de orden de compra',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código interno de recepción (ej: REC-2025-0001)', max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('document_type', models.CharField(blank=True, help_text='Factura, guía, etc.', max_length=50, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reception_date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('transport_company', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature_recorded', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura registrada al ingreso (si aplica)', max_digits=5, null=True)),
                ('num_boxes', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('RECEIVED', 'Recibido en bodega'), ('UNDER_QA', 'En inspección'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='procurement.purchaseorder', verbose_name='Orden de compra asociada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Materia Prima',
                'verbose_name_plural': 'Recepciones de Materia Prima',
                'ordering': ['-reception_date', '-code'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialReceptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad esperada según factura/OC', max_digits=12, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=4, help_text='Cantidad realmente recibida', max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('supplier_lot', models.CharField(blank=True, help_text='Lote según etiqueta del proveedor (si existe)', max_length=50, null=True)),
                ('internal_lot', models.CharField(blank=True, help_text='Lote interno asignado por la empresa (si ya lo tienes al recibir)', max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Fecha de vencimiento indicada por el proveedor.', null=True, verbose_name='Fecha de caducidad')),
                ('storage_area', models.CharField(blank=True, help_text='Área/bodega de almacenamiento inicial', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reception_lines', to='inventory.product')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.rawmaterialreception')),
            ],
            options={
                'verbose_name': 'Línea de Recepción de Materia Prima',
                'verbose_name_plural': 'Líneas de Recepción de Materia Prima',
            },
        ),
    ]
