# Generated by Django 5.2.7 on 2026-01-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialreceptionline',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se recibió el material (puede diferir de la base)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Unidad de medida recibida'),
        ),
    ]
