# Generated by Django 5.2.7 on 2026-01-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('procurement', '0002_add_unit_field_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialreceptionline',
            name='unit',
            field=models.ForeignKey(help_text='Unidad en la que se recibió el material (puede diferir de la base)', on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='Unidad de medida recibida'),
        ),
    ]
