# Generated by Django 5.2.7 on 2026-01-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_make_unit_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialreceptionline',
            name='manufacturing_date',
            field=models.DateField(blank=True, help_text='Fecha de elaboración/fabricación del lote.', null=True, verbose_name='Fecha de elaboración'),
        ),
    ]
