# Generated by Django 5.2.7 on 2026-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rawmaterialreceptionline_manufacturing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialreceptionline',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Número de lote único (puede ser del proveedor o auto-generado). Este será el lote usado en todo el sistema para trazabilidad.', max_length=50, null=True, verbose_name='Número de lote'),
        ),
        migrations.AlterField(
            model_name='rawmaterialreceptionline',
            name='internal_lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialreceptionline',
            name='supplier_lot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
