# Generated by Django 5.2.7 on 2026-02-11 12:03

from django.db import migrations


def consolidate_reception_lot_numbers(apps, schema_editor):
    """
    Consolida supplier_lot e internal_lot en un solo campo lot_number.
    Prioridad: supplier_lot si existe, sino internal_lot.
    """
    RawMaterialReceptionLine = apps.get_model('procurement', 'RawMaterialReceptionLine')

    for line in RawMaterialReceptionLine.objects.all():
        # Priorizar lote del proveedor si existe
        if line.supplier_lot:
            line.lot_number = line.supplier_lot
        elif line.internal_lot:
            line.lot_number = line.internal_lot
        # Si no hay ninguno, dejar vacío (se generará en la recepción)

        line.save(update_fields=['lot_number'])


def reverse_consolidate(apps, schema_editor):
    """
    Reversión: copiar lot_number de vuelta a supplier_lot
    """
    RawMaterialReceptionLine = apps.get_model('procurement', 'RawMaterialReceptionLine')

    for line in RawMaterialReceptionLine.objects.all():
        if line.lot_number and not line.supplier_lot:
            line.supplier_lot = line.lot_number
            line.save(update_fields=['supplier_lot'])


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_rawmaterialreceptionline_lot_number_and_more'),
    ]

    operations = [
        migrations.RunPython(consolidate_reception_lot_numbers, reverse_consolidate),
    ]
