# Generated by Django 5.2.7 on 2026-01-31 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledispatch',
            options={'ordering': ['-dispatched_date'], 'verbose_name': 'Despacho de venta', 'verbose_name_plural': 'Despachos de venta'},
        ),
        migrations.RemoveField(
            model_name='saledispatch',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='saledispatch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='saledispatch',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='saledispatch',
            name='code',
            field=models.CharField(blank=True, help_text='DS-2026-0001', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='saledispatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmado'), ('DISPATCHED', 'Despachado'), ('INVOICED', 'Facturado'), ('CANCELED', 'Cancelado')], default='INVOICED', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='xml_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmado'), ('DISPATCHED', 'Despachado'), ('INVOICED', 'Facturado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SaleDispatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saledispatch')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_dispatch_lines', to='inventory.lot')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='sales.saleorderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
