# Generated by Django 5.2.7 on 2026-01-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('partners', '0001_initial'),
        ('sales', '0002_alter_saledispatch_options_remove_saledispatch_lot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledispatch',
            name='code',
            field=models.CharField(blank=True, help_text='DS-2026-0001', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='saledispatch',
            name='dispatched_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de despacho'),
        ),
        migrations.AlterField(
            model_name='saledispatch',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='saledispatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='sales.saleorder', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='saledispatchline',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saledispatch', verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='saledispatchline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_dispatch_lines', to='inventory.lot', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='saledispatchline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='sales.saleorderline', verbose_name='Línea de pedido'),
        ),
        migrations.AlterField(
            model_name='saledispatchline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='saledispatchline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='client',
            field=models.ForeignKey(help_text='Cliente que realiza el pedido.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='partners.partner', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='code',
            field=models.CharField(help_text='Código interno del pedido (ej. SO-2026-0001)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='delivery_date',
            field=models.DateField(help_text='Fecha de entrega del pedido.', verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmado'), ('DISPATCHED', 'Despachado'), ('INVOICED', 'Facturado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_order_lines', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario'),
        ),
    ]
