# Generated by Django 5.2.7 on 2026-01-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('sales', '0003_alter_saledispatch_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmado'), ('PICKING', 'En picking'), ('PACKING', 'En packing'), ('DISPATCHED', 'Despachado'), ('INVOICED', 'Facturado'), ('CANCELED', 'Cancelado')], default='INVOICED', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmado'), ('PICKING', 'En picking'), ('PACKING', 'En packing'), ('DISPATCHED', 'Despachado'), ('INVOICED', 'Facturado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PackingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='PA-2026-0001', max_length=50, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('num_boxes', models.PositiveIntegerField(default=0, verbose_name='Número de cajas')),
                ('gross_weight', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Peso bruto (kg)')),
                ('net_weight', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Peso neto (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packings', to='sales.saleorder', verbose_name='Pedido')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de packing',
                'verbose_name_plural': 'Órdenes de packing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('box_number', models.PositiveIntegerField(default=1, verbose_name='N° de caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.lot', verbose_name='Lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.packingorder', verbose_name='Packing')),
            ],
            options={
                'verbose_name': 'Línea de packing',
                'verbose_name_plural': 'Líneas de packing',
            },
        ),
        migrations.CreateModel(
            name='PickingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, help_text='PK-2026-0001', max_length=50, unique=True, verbose_name='Código')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickings', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickings', to='sales.saleorder', verbose_name='Pedido')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de picking',
                'verbose_name_plural': 'Órdenes de picking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('quantity_requested', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad solicitada')),
                ('quantity_picked', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad recogida')),
                ('picked', models.BooleanField(default=False, verbose_name='Recogido')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.lot', verbose_name='Lote')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_lines', to='sales.saleorderline', verbose_name='Línea de pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.pickingorder', verbose_name='Picking')),
            ],
            options={
                'verbose_name': 'Línea de picking',
                'verbose_name_plural': 'Líneas de picking',
            },
        ),
        migrations.AddField(
            model_name='packingorder',
            name='picking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='sales.pickingorder', verbose_name='Picking'),
        ),
    ]
