# Generated by Django 5.2.7 on 2026-02-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('sales', '0004_alter_saleinvoice_status_alter_saleorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='access_key',
            field=models.CharField(default='', max_length=49, unique=True, verbose_name='Clave de acceso'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='authorization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='authorization_number',
            field=models.CharField(blank=True, max_length=49, verbose_name='Nº autorización'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_identification',
            field=models.CharField(default='', max_length=20, verbose_name='Identificación comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_identification_type',
            field=models.CharField(default='04', max_length=2, verbose_name='Tipo ID comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_legal_name',
            field=models.CharField(default='', max_length=300, verbose_name='Razón social comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.saledispatch', verbose_name='Despacho'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='emission_point',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de emisión'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='establishment',
            field=models.CharField(default='001', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='sequential',
            field=models.CharField(default='000000000', max_length=9, verbose_name='Secuencial'),
        ),
        migrations.AlterUniqueTogether(
            name='saleinvoice',
            unique_together={('establishment', 'emission_point', 'sequential')},
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='sri_response',
            field=models.TextField(blank=True, verbose_name='Respuesta SRI'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='subtotal_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal IVA'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='subtotal_no_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal 0%'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total descuento'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='xml_signed',
            field=models.TextField(blank=True, verbose_name='XML firmado'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='xml_unsigned',
            field=models.TextField(blank=True, verbose_name='XML sin firmar'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.saleorder', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado al SRI'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='SaleInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('tax_code', models.CharField(default='2', help_text='2=IVA', max_length=2, verbose_name='Código impuesto')),
                ('tax_rate_code', models.CharField(default='2', help_text='0=0%, 2=12%, 3=14%, 4=15%', max_length=4, verbose_name='Código tarifa')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarifa %')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor impuesto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleinvoice', verbose_name='Factura')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de factura',
                'verbose_name_plural': 'Líneas de factura',
            },
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='invoice_code',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='sri_status',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='xml_data',
        ),
    ]
