# Generated by Django 5.2.7 on 2026-02-01 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('partners', '0002_partner_driver_identification_partner_driver_name_and_more'),
        ('sales', '0005_alter_saleinvoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.CharField(default='001', max_length=3, verbose_name='Establecimiento')),
                ('emission_point', models.CharField(default='001', max_length=3, verbose_name='Punto de emisión')),
                ('sequential', models.CharField(default='000000000', max_length=9, verbose_name='Secuencial')),
                ('access_key', models.CharField(default='', max_length=49, unique=True, verbose_name='Clave de acceso')),
                ('carrier_legal_name', models.CharField(max_length=300, verbose_name='Razón social transportista')),
                ('carrier_identification_type', models.CharField(default='04', max_length=2, verbose_name='Tipo ID transportista')),
                ('carrier_identification', models.CharField(max_length=20, verbose_name='RUC/Cédula transportista')),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('driver_name', models.CharField(blank=True, max_length=200, verbose_name='Conductor')),
                ('driver_identification', models.CharField(blank=True, max_length=20, verbose_name='Cédula conductor')),
                ('transport_start_date', models.DateField(verbose_name='Fecha inicio transporte')),
                ('transport_end_date', models.DateField(verbose_name='Fecha fin transporte')),
                ('recipient_identification_type', models.CharField(default='04', max_length=2, verbose_name='Tipo ID destinatario')),
                ('recipient_identification', models.CharField(max_length=20, verbose_name='Identificación destinatario')),
                ('recipient_legal_name', models.CharField(max_length=300, verbose_name='Razón social destinatario')),
                ('recipient_address', models.CharField(max_length=300, verbose_name='Dirección destinatario')),
                ('origin_address', models.CharField(max_length=300, verbose_name='Dirección de partida')),
                ('transfer_reason', models.CharField(default='Venta', max_length=300, verbose_name='Motivo traslado')),
                ('route', models.CharField(blank=True, max_length=300, verbose_name='Ruta')),
                ('supporting_doc_type', models.CharField(default='01', max_length=2, verbose_name='Tipo doc sustento')),
                ('supporting_doc_number', models.CharField(blank=True, max_length=17, verbose_name='Nº doc sustento')),
                ('supporting_doc_authorization', models.CharField(blank=True, max_length=49, verbose_name='Autorización doc sustento')),
                ('supporting_doc_date', models.DateField(blank=True, null=True, verbose_name='Fecha emisión doc sustento')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SIGNED', 'Firmado'), ('SENT', 'Enviado al SRI'), ('AUTHORIZED', 'Autorizado'), ('REJECTED', 'Rechazado'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('authorization_number', models.CharField(blank=True, max_length=49, verbose_name='Nº autorización')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización')),
                ('xml_unsigned', models.TextField(blank=True, verbose_name='XML sin firmar')),
                ('xml_signed', models.TextField(blank=True, verbose_name='XML firmado')),
                ('sri_response', models.TextField(blank=True, verbose_name='Respuesta SRI')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('carrier', models.ForeignKey(limit_choices_to={'is_carrier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='guias_as_carrier', to='partners.partner', verbose_name='Transportista')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_remision', to='sales.saledispatch', verbose_name='Despacho')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_remision', to='sales.saleorder', verbose_name='Pedido')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guía de remisión',
                'verbose_name_plural': 'Guías de remisión',
                'ordering': ['-issue_date'],
                'unique_together': {('establishment', 'emission_point', 'sequential')},
            },
        ),
        migrations.CreateModel(
            name='GuiaRemisionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.guiaremision', verbose_name='Guía de remisión')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de guía de remisión',
                'verbose_name_plural': 'Líneas de guía de remisión',
            },
        ),
    ]
