# Generated by Django 5.2.7 on 2026-02-03 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_quantity'),
        ('sales', '0007_creditnote_creditnoteline_productrecall_salereturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturn',
            name='dispatch',
        ),
        migrations.RemoveField(
            model_name='salereturn',
            name='order',
        ),
        migrations.RemoveField(
            model_name='salereturnline',
            name='dispatch_line',
        ),
        migrations.AddField(
            model_name='salereturn',
            name='client_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='client_identification',
            field=models.CharField(default='', max_length=20, verbose_name='RUC/CI Cliente'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='client_legal_name',
            field=models.CharField(default='', max_length=300, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='inspection_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inspección'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='inspection_notes',
            field=models.TextField(blank=True, verbose_name='Notas de inspección QA'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleinvoice', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='reason_notes',
            field=models.TextField(blank=True, verbose_name='Observaciones del motivo'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleinvoiceline', verbose_name='Línea de factura'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generada'), ('RECEIVED', 'Producto Recibido'), ('PENDING_INSPECTION', 'Por Inspeccionar'), ('APPROVED', 'Aprobada (ingresó a stock)'), ('REJECTED', 'Rechazada (producto dado de baja)'), ('CANCELED', 'Cancelada')], default='GENERATED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salereturnline',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Lote del producto devuelto', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.lot', verbose_name='Lote'),
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('reason_type', models.CharField(choices=[('COMMERCIAL', 'Comercial'), ('NON_CONFORMITY', 'No Conformidad del Producto')], default='COMMERCIAL', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivo de devolución',
                'verbose_name_plural': 'Motivos de devolución',
                'ordering': ['reason_type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.returnreason', verbose_name='Motivo'),
        ),
    ]
