# Generated by Django 5.2.7 on 2026-02-04 11:21
# Fixed: Tables already dropped in 0009, so this migration only cleans up Django state

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_recall_add_delivery'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='recalldispatch',
                    name='recall',
                ),
                migrations.RemoveField(
                    model_name='recalllot',
                    name='recall',
                ),
                migrations.AlterUniqueTogether(
                    name='recalldispatch',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='recalldispatch',
                    name='client',
                ),
                migrations.RemoveField(
                    model_name='recalldispatch',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='recalldispatch',
                    name='dispatch',
                ),
                migrations.RemoveField(
                    model_name='recalldispatch',
                    name='updated_by',
                ),
                migrations.AlterUniqueTogether(
                    name='recalllot',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='recalllot',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='recalllot',
                    name='lot',
                ),
                migrations.RemoveField(
                    model_name='recalllot',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='recalllot',
                    name='updated_by',
                ),
                migrations.DeleteModel(
                    name='ProductRecall',
                ),
                migrations.DeleteModel(
                    name='RecallDispatch',
                ),
                migrations.DeleteModel(
                    name='RecallLot',
                ),
            ],
            database_operations=[],
        ),
    ]
