# Generated by Django 5.2.7 on 2026-02-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_cleanup_recall_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='delivery_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto'),
        ),
    ]
