# Generated by Django 5.2.7 on 2026-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_saleorder_delivery_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad comprador'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono comprador'),
        ),
    ]
